unstable_features = true
format_code_in_doc_comments = true
hard_tabs = true
imports_layout = "vertical"
imports_granularity = "crate"
newline_style = "unix"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true # replaces try! with ?
# blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
color = "never"
wrap_comments = true
edition = "2021"
format_macro_matchers = true
format_macro_bodies = true
reorder_impl_items = true
print_misformatted_file_names = true