[workspace]
resolver = "2"
members = [
	"mappings",
	"cli",
	"plugin",
	"nih_plug_egui",
	"bundler",
	"print-notes",
]

[profile.release]
panic = "abort"
lto = "thin"
strip = "debuginfo"

[profile.dev]
opt-level = 1
