{
  "name": "All",
  "on": {
    "push": {
      "paths-ignore": [
        "**.md",
        "build.sh",
        "*.mid",
        "LICENSE"
      ]
    },
    "pull_request": {
      "paths-ignore": [
        "**.md",
        "*.mid",
        "build.sh",
        "LICENSE"
      ]
    }
  },
  "jobs": {
    "test": {
      "strategy": {
        "matrix": {
          "os": ["windows-latest", "ubuntu-latest", "macos-latest"]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Prep | Dependencies",
          "if": "matrix.os == 'ubuntu-latest'",
          "run": "sudo apt-get update && sudo apt-get install -y libgl-dev libx11-dev libxcursor-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev libxcb-dri2-0-dev libx11-xcb-dev"
        },
        {
          "name": "Check | Tests",
          "run": "cargo test -q --bin drum-mapper --lib drum-mapper"
        }
      ]
    },
    "build": {
      "name": "Build Release Binaries",
      "needs": "test",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "continue-on-error": true,
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "include": [
            {
              "name": "drum-mapper-x86_64-windows.zip",
              "os": "windows-latest",
              "target": "x86_64-pc-windows-msvc"
            },
            {
              "name": "drum-mapper-x86_64-linux.tar.xz",
              "os": "ubuntu-latest",
              "target": "x86_64-unknown-linux-gnu"
            },
            {
              "name": "drum-mapper-x86_64-macos.tar.xz",
              "os": "macos-latest",
              "target": "x86_64-apple-darwin"
            }
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Prep | Dependencies",
          "if": "matrix.os == 'ubuntu-latest'",
          "run": "sudo apt-get update && sudo apt-get install -y libgl-dev libx11-dev libxcursor-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev libxcb-dri2-0-dev libx11-xcb-dev"
        },
        {
          "name": "Build | Plugin",
          "run": "cargo run -q --bin bundler -- bundle drum-mapper -q --target ${{ matrix.target }} --release"
        },
        {
          "name": "Build | CLI",
          "env": { "RUSTFLAGS": "-Cstrip=debuginfo" },
          "run": "cargo build --bin drum-mapper -q --release --target ${{ matrix.target }}"
        },
        {
          "name": "PostBuild | Prepare",
          "if": "matrix.os != 'windows-latest'",
          "shell": "bash",
          "run": "mkdir out; mv './target/${{ matrix.target }}/release/drum-mapper' LICENSE ./target/bundled/* ./out/; cd ./out; tar cJf ../${{ matrix.name }} ./*; cd .."
        },
        {
          "name": "PostBuild | Prepare",
          "if": "matrix.os == 'windows-latest'",
          "run": "$ErrorActionPreference = 'stop'; mkdir out; mv LICENSE, target/${{ matrix.target }}/release/drum-mapper.exe, target/bundled/* ./out/; cd out; 7z a ../${{ matrix.name }} *; cd .."
        },
        {
          "name": "Deploy | Upload Artifacts",
          "uses": "actions/upload-artifact@v3",
          "with": {
            "name": "${{ matrix.name }}",
            "path": "${{ matrix.name }}"
          }
        }
      ]
    },
    "release": {
      "name": "Create GitHub Release",
      "needs": "build",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v3",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "Setup | Artifacts",
          "uses": "actions/download-artifact@v3"
        },
        {
          "name": "Deploy | Publish",
          "uses": "softprops/action-gh-release@v1",
          "with": {
            "files": "drum-mapper*/drum-mapper*"
          }
        }
      ]
    }
  }
}